version: '2'
services:

  oauth2-server:
    build: .
    environment:
      oauth-server_stores__redis__host: redis
    links:
      - redis
    volumes:
      - ./:/app
    ports:
      - "8080:8080"


  redis:
    image: redis
    ports:
      - "6379:6379"
